import type { CartData, ProductData, ShippingRate } from './types';

export const MOCK_CART: CartData = {
  token: 'c1-abc123def456?key=mock1234567890abcdef1234567890abcd',
  note: 'Please gift wrap the blue t-shirt',
  attributes: {
    'Gift wrap': 'Yes',
    'Delivery instructions': 'Leave at door',
  },
  original_total_price: 22495,
  total_price: 20695,
  total_discount: 1800,
  total_weight: 1550,
  item_count: 5,
  items: [
    // Item 1 — Simple product, no properties
    {
      id: 44012345678901,
      key: '44012345678901:abc1def2ghi3jkl4mno5pqr6stu7vwx8',
      properties: null,
      quantity: 2,
      variant_id: 44012345678901,
      product_id: 8001234567890,
      title: 'Classic T-Shirt - Blue / Medium',
      product_title: 'Classic T-Shirt',
      product_description: 'A comfortable everyday tee made from 100% organic cotton.',
      product_type: 'Shirts',
      vendor: 'Acme Apparel',
      variant_title: 'Blue / Medium',
      variant_options: ['Blue', 'Medium'],
      options_with_values: [
        { name: 'Color', value: 'Blue' },
        { name: 'Size', value: 'Medium' },
      ],
      sku: 'TS-BLU-M',
      grams: 200,
      taxable: true,
      requires_shipping: true,
      product_has_only_default_variant: false,
      gift_card: false,
      final_price: 2999,
      final_line_price: 5998,
      url: '/products/classic-t-shirt?variant=44012345678901',
      image: 'https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-product-1_large.png',
      featured_image: {
        url: 'https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-product-1_large.png',
        aspect_ratio: 1.0,
        alt: 'Classic T-Shirt Blue',
        height: 1200,
        width: 1200,
      },
      handle: 'classic-t-shirt',
      price: 2999,
      original_price: 2999,
      presentment_price: 29.99,
      discounted_price: 2999,
      line_price: 5998,
      original_line_price: 5998,
      total_discount: 0,
      discounts: [],
      line_level_discount_allocations: [],
      line_level_total_discount: 0,
      quantity_rule: { min: 1, max: null, increment: 1 },
      has_components: false,
      selling_plan_allocation: null,
    },
    // Item 2 — Product with line item properties
    {
      id: 44012345678902,
      key: '44012345678902:def2abc1ghi3jkl4mno5pqr6stu7vwx8',
      properties: {
        Engraving: 'To my love',
        Font: 'Script',
      },
      quantity: 1,
      variant_id: 44012345678902,
      product_id: 8001234567891,
      title: 'Custom Engraved Bracelet - Gold',
      product_title: 'Custom Engraved Bracelet',
      product_description: 'A beautiful gold bracelet with custom engraving.',
      product_type: 'Jewelry',
      vendor: 'Luxe Accessories',
      variant_title: 'Gold',
      variant_options: ['Gold'],
      options_with_values: [{ name: 'Material', value: 'Gold' }],
      sku: 'BRC-GLD-001',
      grams: 50,
      taxable: true,
      requires_shipping: true,
      product_has_only_default_variant: false,
      gift_card: false,
      final_price: 4999,
      final_line_price: 4999,
      url: '/products/custom-engraved-bracelet?variant=44012345678902',
      image: 'https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-product-2_large.png',
      featured_image: {
        url: 'https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-product-2_large.png',
        aspect_ratio: 1.0,
        alt: 'Custom Engraved Bracelet Gold',
        height: 1200,
        width: 1200,
      },
      handle: 'custom-engraved-bracelet',
      price: 4999,
      original_price: 4999,
      presentment_price: 49.99,
      discounted_price: 4999,
      line_price: 4999,
      original_line_price: 4999,
      total_discount: 0,
      discounts: [],
      line_level_discount_allocations: [],
      line_level_total_discount: 0,
      quantity_rule: { min: 1, max: null, increment: 1 },
      has_components: false,
      selling_plan_allocation: null,
    },
    // Item 3 — Product with selling plan (subscription)
    {
      id: 44012345678903,
      key: '44012345678903:ghi3abc1def2jkl4mno5pqr6stu7vwx8',
      properties: null,
      quantity: 1,
      variant_id: 44012345678903,
      product_id: 8001234567892,
      title: 'Organic Coffee Beans - 1kg',
      product_title: 'Organic Coffee Beans',
      product_description: 'Single-origin organic coffee beans, freshly roasted.',
      product_type: 'Coffee',
      vendor: 'Bean Co.',
      variant_title: '1kg',
      variant_options: ['1kg'],
      options_with_values: [{ name: 'Size', value: '1kg' }],
      sku: 'COF-ORG-1KG',
      grams: 1000,
      taxable: true,
      requires_shipping: true,
      product_has_only_default_variant: false,
      gift_card: false,
      final_price: 2499,
      final_line_price: 2499,
      url: '/products/organic-coffee-beans?selling_plan=1001&variant=44012345678903',
      image: 'https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-product-3_large.png',
      featured_image: {
        url: 'https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-product-3_large.png',
        aspect_ratio: 1.0,
        alt: 'Organic Coffee Beans 1kg',
        height: 1200,
        width: 1200,
      },
      handle: 'organic-coffee-beans',
      price: 2499,
      original_price: 2499,
      presentment_price: 24.99,
      discounted_price: 2124,
      line_price: 2499,
      original_line_price: 2499,
      total_discount: 0,
      discounts: [],
      line_level_discount_allocations: [],
      line_level_total_discount: 0,
      quantity_rule: { min: 1, max: null, increment: 1 },
      has_components: false,
      selling_plan_allocation: {
        price: 2124,
        compare_at_price: 2499,
        per_delivery_price: 2124,
        price_adjustments: [{ position: 1, price: 2499 }],
        selling_plan: {
          id: 1001,
          name: 'Deliver every month — save 15%',
          description: null,
          options: [
            { name: 'Delivery every', position: 1, value: 'month' },
          ],
          recurring_deliveries: true,
          fixed_selling_plan: false,
          price_adjustments: [
            { order_count: null, position: 1, value_type: 'percentage', value: 15 },
          ],
        },
      },
    },
    // Item 4 — Product with discount applied
    {
      id: 44012345678904,
      key: '44012345678904:jkl4abc1def2ghi3mno5pqr6stu7vwx8',
      properties: null,
      quantity: 1,
      variant_id: 44012345678904,
      product_id: 8001234567893,
      title: 'Wireless Headphones - Black',
      product_title: 'Wireless Headphones',
      product_description: 'Premium noise-canceling wireless headphones.',
      product_type: 'Electronics',
      vendor: 'SoundMax',
      variant_title: 'Black',
      variant_options: ['Black'],
      options_with_values: [{ name: 'Color', value: 'Black' }],
      sku: 'HP-WL-BLK',
      grams: 300,
      taxable: true,
      requires_shipping: true,
      product_has_only_default_variant: false,
      gift_card: false,
      final_price: 7199,
      final_line_price: 7199,
      url: '/products/wireless-headphones?variant=44012345678904',
      image: 'https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-product-4_large.png',
      featured_image: {
        url: 'https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-product-4_large.png',
        aspect_ratio: 1.0,
        alt: 'Wireless Headphones Black',
        height: 1200,
        width: 1200,
      },
      handle: 'wireless-headphones',
      price: 8999,
      original_price: 8999,
      presentment_price: 89.99,
      discounted_price: 7199,
      line_price: 7199,
      original_line_price: 8999,
      total_discount: 1800,
      discounts: [{ amount: 1800, title: 'SUMMER20' }],
      line_level_discount_allocations: [
        {
          amount: 1800,
          discount_application: {
            type: 'discount_code',
            key: 'summer20-abc123',
            title: 'SUMMER20',
            description: null,
            value: '20.0',
            value_type: 'percentage',
            total_allocated_amount: 1800,
            target_type: 'line_item',
            target_selection: 'entitled',
            created_at: '2026-03-01T12:00:00.000Z',
            allocation_method: 'each',
          },
        },
      ],
      line_level_total_discount: 1800,
      quantity_rule: { min: 1, max: null, increment: 1 },
      has_components: false,
      selling_plan_allocation: null,
    },
  ],
  requires_shipping: true,
  currency: 'USD',
  items_subtotal_price: 22495,
  cart_level_discount_applications: [
    {
      type: 'discount_code',
      title: 'SUMMER20',
      description: null,
      value: '20.0',
      value_type: 'percentage',
      total_allocated_amount: 1800,
      target_type: 'line_item',
      target_selection: 'entitled',
    },
  ],
  discount_codes: [
    { code: 'SUMMER20', amount: 1800, type: 'percentage' },
  ],
};

export const MOCK_PRODUCT: ProductData = {
  id: 8001234567900,
  title: 'Classic Leather Wallet',
  handle: 'classic-leather-wallet',
  description: 'A timeless leather wallet with multiple card slots and a bill compartment. Handcrafted from full-grain leather.',
  vendor: 'Heritage Goods',
  type: 'Accessories',
  tags: ['leather', 'wallet', 'accessories', 'gift'],
  images: [
    'https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-product-5_large.png',
    'https://cdn.shopify.com/s/files/1/0533/2089/files/placeholder-images-product-6_large.png',
  ],
  variants: [
    {
      id: 44099900001,
      title: 'Brown',
      option1: 'Brown',
      option2: null,
      option3: null,
      price: 3999,
      compare_at_price: null,
      available: true,
      sku: 'WLT-BRN',
      requires_shipping: true,
      taxable: true,
      featured_image: null,
      requires_selling_plan: false,
      quantity_rule: { min: 1, max: null, increment: 1 },
      selling_plan_allocations: [
        {
          price_adjustments: [{ position: 1, price: 3599 }],
          price: 3599,
          compare_at_price: 3999,
          per_delivery_price: 3599,
          selling_plan_id: 2001,
          selling_plan_group_id: 'sp-group-2001',
        },
        {
          price_adjustments: [{ position: 1, price: 3799 }],
          price: 3799,
          compare_at_price: 3999,
          per_delivery_price: 3799,
          selling_plan_id: 2002,
          selling_plan_group_id: 'sp-group-2001',
        },
      ],
    },
    {
      id: 44099900002,
      title: 'Black',
      option1: 'Black',
      option2: null,
      option3: null,
      price: 3999,
      compare_at_price: null,
      available: true,
      sku: 'WLT-BLK',
      requires_shipping: true,
      taxable: true,
      featured_image: null,
      requires_selling_plan: false,
      quantity_rule: { min: 1, max: null, increment: 1 },
      selling_plan_allocations: [
        {
          price_adjustments: [{ position: 1, price: 3599 }],
          price: 3599,
          compare_at_price: 3999,
          per_delivery_price: 3599,
          selling_plan_id: 2001,
          selling_plan_group_id: 'sp-group-2001',
        },
        {
          price_adjustments: [{ position: 1, price: 3799 }],
          price: 3799,
          compare_at_price: 3999,
          per_delivery_price: 3799,
          selling_plan_id: 2002,
          selling_plan_group_id: 'sp-group-2001',
        },
      ],
    },
    {
      id: 44099900003,
      title: 'Tan',
      option1: 'Tan',
      option2: null,
      option3: null,
      price: 4499,
      compare_at_price: 5999,
      available: false,
      sku: 'WLT-TAN',
      requires_shipping: true,
      taxable: true,
      featured_image: null,
      requires_selling_plan: false,
      quantity_rule: { min: 1, max: null, increment: 1 },
      selling_plan_allocations: [],
    },
  ],
  options: [
    { name: 'Color', position: 1, values: ['Brown', 'Black', 'Tan'] },
  ],
  selling_plan_groups: [
    {
      id: 'sp-group-2001',
      name: 'Subscribe & Save',
      options: [{ name: 'Delivery frequency', position: 1, values: ['1 Month', '3 Months'] }],
      selling_plans: [
        {
          id: 2001,
          name: 'Deliver every month — save 10%',
          description: null,
          options: [{ name: 'Delivery frequency', position: 1, value: '1 Month' }],
          recurring_deliveries: true,
          price_adjustments: [{ order_count: null, position: 1, value_type: 'percentage', value: 10 }],
        },
        {
          id: 2002,
          name: 'Deliver every 3 months — save 5%',
          description: null,
          options: [{ name: 'Delivery frequency', position: 1, value: '3 Months' }],
          recurring_deliveries: true,
          price_adjustments: [{ order_count: null, position: 1, value_type: 'percentage', value: 5 }],
        },
      ],
    },
  ],
};

export const MOCK_SHIPPING_RATES: ShippingRate[] = [
  { name: 'Standard Shipping', code: 'standard', price: '5.99', source: 'shopify', delivery_date: null, delivery_days: 7 },
  { name: 'Express Shipping', code: 'express', price: '12.99', source: 'shopify', delivery_date: null, delivery_days: 3 },
  { name: 'Overnight', code: 'overnight', price: '24.99', source: 'shopify', delivery_date: null, delivery_days: 1 },
];
