// Single source of truth for analytics action names. The Supabase track edge
// function keeps its own VALID_ACTIONS literal (Deno can't import extension
// code), but utils/analytics-actions.test.ts asserts the two lists match, so
// drift fails `bun test` instead of silently dropping events server-side
// (which is exactly what happened to the images_* events in v2026.06.05).
export const ANALYTICS_ACTIONS = [
  'open_in_admin',
  'open_in_customizer',
  'copy_product_json',
  'copy_cart_json',
  'copy_theme_preview_url',
  'clear_cart',
  'save_preset',
  'apply_preset',
  'preset_auto_submit',
  'request_access_context_menu',
  'appstore_partner_table_view',
  'appstore_partner_table_sort',
  'appstore_partner_table_export',
  'open_section_in_code_editor',
  'disable_theme_inspector',
  'resize_theme_customizer',
  'toggle_admin_sidebar',
  'detect_theme',
  'autofill_storefront_password',
  'open_image_in_admin',
  'exit_theme_preview',
  'theme_list_copy_id',
  'theme_list_copy_preview_url',
  'cartograph_open',
  'cartograph_add_item',
  'cartograph_update_quantity',
  'cartograph_remove_item',
  'cartograph_clear',
  'cartograph_apply_discount',
  'cartograph_update_note',
  'cartograph_calculate_shipping',
  'cartograph_update_properties',
  'cartograph_switch_variant',
  'cartograph_update_attributes',
  'cartograph_remove_discount',
  'cartograph_inspect_json',
  'permission_search',
  'expand_all_permissions',
  'collapse_all_permissions',
  'popup_open',
  'review_nudge_show',
  'review_nudge_click',
  'review_nudge_dismiss',
  'headings_view',
  'headings_scroll_to',
  'headings_copy',
  'headings_toggle_hidden',
  'links_view',
  'links_filter',
  'links_highlight',
  'links_scroll_to',
  'links_export',
  'links_copy',
  'links_sort',
  'links_toggle_hidden',
  'links_check_status',
  'assets_view',
  'assets_filter',
  'assets_export',
  'assets_copy',
  'assets_view_source',
  'assets_expand_inline',
  'assets_sort',
  'images_view',
  'images_filter',
  'images_highlight',
  'images_scroll_to',
  'images_export',
  'images_copy',
  'images_sort',
  'images_open',
  'schema_view',
  'schema_copy',
  'schema_export',
  'robots_view',
  'robots_goto_line',
  'robots_copy',
  'robots_open',
  'robots_ai_toggle',
  'robots_wrap_toggle'
] as const;

export type AnalyticsAction = (typeof ANALYTICS_ACTIONS)[number];
