// Single source of truth for analytics action names. The Supabase track edge
// function keeps its own VALID_ACTIONS literal (Deno can't import extension
// code), but utils/analytics-actions.test.ts asserts the two lists match, so
// drift fails `bun test` instead of silently dropping events server-side
// (which is exactly what happened to the images_* events in v2026.06.05).
export const ANALYTICS_ACTIONS = [
  'open_in_admin',
  'open_in_customizer',
  'copy_product_json',
  'copy_cart_json',
  'copy_theme_preview_url',
  'clear_cart',
  'save_preset',
  'apply_preset',
  'preset_auto_submit',
  'request_access_context_menu',
  'appstore_partner_table_view',
  'appstore_partner_table_sort',
  'appstore_partner_table_export',
  'compare_add_app',
  'compare_view',
  'compare_export_markdown',
  'compare_export_csv',
  'compare_export_json',
  'compare_share',
  'open_section_in_code_editor',
  'disable_theme_inspector',
  'resize_theme_customizer',
  'toggle_admin_sidebar',
  'detect_theme',
  'autofill_storefront_password',
  'open_image_in_admin',
  'exit_theme_preview',
  'theme_list_copy_id',
  'theme_list_copy_preview_url',
  'cartograph_open',
  'cartograph_add_item',
  'cartograph_update_quantity',
  'cartograph_remove_item',
  'cartograph_clear',
  'cartograph_apply_discount',
  'cartograph_update_note',
  'cartograph_calculate_shipping',
  'cartograph_update_properties',
  'cartograph_switch_variant',
  'cartograph_update_attributes',
  'cartograph_remove_discount',
  'cartograph_inspect_json',
  'permission_search',
  'expand_all_permissions',
  'collapse_all_permissions',
  'popup_open',
  'review_nudge_show',
  'review_nudge_click',
  'review_nudge_dismiss',
  'overview_view',
  'overview_copy',
  'overview_quick_link',
  'overview_social_profile',
  'headings_view',
  'headings_scroll_to',
  'headings_copy',
  'headings_toggle_hidden',
  'links_view',
  'links_filter',
  'links_highlight',
  'links_scroll_to',
  'links_export',
  'links_copy',
  'links_sort',
  'links_toggle_hidden',
  'links_check_status',
  'assets_view',
  'assets_filter',
  'assets_export',
  'assets_copy',
  'assets_view_source',
  'assets_expand_inline',
  'assets_sort',
  'images_view',
  'images_filter',
  'images_highlight',
  'images_scroll_to',
  'images_export',
  'images_copy',
  'images_sort',
  'images_open',
  'schema_view',
  'schema_copy',
  'schema_export',
  'robots_view',
  'robots_goto_line',
  'robots_copy',
  'robots_open',
  'robots_ai_toggle',
  'robots_wrap_toggle',
  'social_view',
  'social_platform_click',
  'social_copy_tags'
] as const;

export type AnalyticsAction = (typeof ANALYTICS_ACTIONS)[number];

// Time savings per action (in seconds)
export const TIME_SAVINGS: Record<AnalyticsAction, number | ((metadata?: Record<string, unknown>) => number)> = {
  open_in_admin: (metadata) => {
    if (metadata?.page_type === 'homepage') return 10;
    if (['product', 'page', 'article'].includes(metadata?.page_type as string)) return 45;
    return 25;
  },
  open_in_customizer: (metadata) => {
    if (metadata?.page_type === 'homepage') return 20;
    if (['product', 'page', 'article'].includes(metadata?.page_type as string)) return 45;
    return 30;
  },
  copy_product_json: 30,
  copy_cart_json: 30,
  copy_theme_preview_url: 40,
  clear_cart: 30,
  save_preset: 0,
  apply_preset: (metadata) => {
    return 45 + (metadata?.has_custom_message ? 20 : 0);
  },
  preset_auto_submit: 20,
  request_access_context_menu: 30,
  appstore_partner_table_view: (metadata) => Number(metadata?.app_count ?? 0) * 5,
  appstore_partner_table_sort: (metadata) => Number(metadata?.app_count ?? 0) * 2,
  appstore_partner_table_export: (metadata) => Number(metadata?.app_count ?? 0) * 10 + 30,
  compare_add_app: 5,
  compare_view: (metadata) => Number(metadata?.app_count ?? 0) * 45,
  compare_export_markdown: 60,
  compare_export_csv: 60,
  compare_export_json: 60,
  compare_share: 30,
  open_section_in_code_editor: 30,
  disable_theme_inspector: 3,
  resize_theme_customizer: 3,
  toggle_admin_sidebar: 0,
  detect_theme: 30,
  autofill_storefront_password: 10,
  open_image_in_admin: 15,
  exit_theme_preview: 20,
  theme_list_copy_id: 10,
  theme_list_copy_preview_url: 10,
  cartograph_open: 0,
  cartograph_add_item: 60,
  cartograph_update_quantity: 15,
  cartograph_remove_item: 15,
  cartograph_clear: 30,
  cartograph_apply_discount: 20,
  cartograph_update_note: 15,
  cartograph_calculate_shipping: 60,
  cartograph_update_properties: 60,
  cartograph_switch_variant: 120,
  cartograph_update_attributes: 60,
  cartograph_remove_discount: 15,
  cartograph_inspect_json: 45,
  permission_search: 20,
  expand_all_permissions: 10,
  collapse_all_permissions: 10,
  popup_open: 0,
  review_nudge_show: 0,
  review_nudge_click: 0,
  review_nudge_dismiss: 0,
  overview_view: 60,
  overview_copy: 30,
  overview_quick_link: 5,
  overview_social_profile: 30,
  headings_view: 60,
  headings_scroll_to: 5,
  headings_copy: 30,
  headings_toggle_hidden: 5,
  links_view: 60,
  links_filter: 25,
  links_highlight: 10,
  links_scroll_to: 5,
  links_export: 60,
  links_copy: 60,
  links_sort: 25,
  links_toggle_hidden: 5,
  links_check_status: (metadata) => Number(metadata?.count ?? 0) * 5 + 15,
  assets_view: 60,
  assets_filter: 25,
  assets_export: 60,
  assets_copy: 60,
  assets_view_source: 5,
  assets_expand_inline: 5,
  assets_sort: 60,
  images_view: 60,
  images_filter: 25,
  images_highlight: 10,
  images_scroll_to: 5,
  images_export: 60,
  images_copy: 60,
  images_sort: 25,
  images_open: 5,
  schema_view: 60,
  schema_copy: 60,
  schema_export: 60,
  robots_view: 90,
  robots_goto_line: 5,
  robots_copy: 30,
  robots_open: 5,
  robots_ai_toggle: 5,
  robots_wrap_toggle: 0,
  social_view: 120,
  social_platform_click: 5,
  social_copy_tags: 20
};

export const COOLDOWN_MS: Partial<Record<AnalyticsAction, number>> = {
  detect_theme: 5 * 60 * 1000
};
