import { CWS_URL } from './constants';

/**
 * Appends a "Generated by Alfred" footer to report-style text blobs
 * (formatted copies and exports). Not for raw data copies like URL
 * lists or JSON, which must stay clean.
 */
export function withCredit(text: string): string {
  return `${text}\n\n--\nGenerated by Alfred for Shopify · ${CWS_URL}`;
}

/**
 * CSV variant: a blank line then a single-cell credit row, so spreadsheet
 * apps render it as a detached footer below the table.
 */
export function withCsvCredit(csv: string): string {
  return `${csv}\n\n\n###\nGenerated by Alfred for Shopify · ${CWS_URL}`;
}
